# Generated by Django 3.1.13 on 2021-10-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictionary_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='picture',
            field=models.ImageField(upload_to='self.name/'),
        ),
    ]
